// Generated by CoffeeScript 1.7.1
(function() {
  var onBridgeReady;
  onBridgeReady = function() {
    WeixinJSBridge.on("menu:share:timeline", function(e) {
      var data, img, url;
      url = location.href;
      img = "" + url + "/god.jpg";
      data = {
        img_url: img,
        img_width: "120",
        img_height: "120",
        link: url,
        desc: "新头像，我骄傲，你也来做个吧！",
        title: "我做了个新头像，邀请你一起玩坏处女座！"
      };
      return WeixinJSBridge.invoke("shareTimeline", data, function(res) {
        return WeixinJSBridge.log(res.err_msg);
      });
    });
    return WeixinJSBridge.on("menu:share:appmessage", function(argv) {
      var url;
      url = location.href;
      return WeixinJSBridge.invoke("sendAppMessage", {
        img_url: img,
        img_width: "120",
        img_height: "120",
        link: url,
        desc: "新头像，我骄傲，你也来做个吧！",
        title: "我做了个新头像，邀请你一起玩坏处女座！"
      }, function(res) {
        return WeixinJSBridge.log(res.err_msg);
      });
    });
  };
  try {
    return document.addEventListener("WeixinJSBridgeReady", function() {
      return onBridgeReady();
    });
  } catch (_error) {}
})();
